# Cluster IP
apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: ClusterIP
  selector:
    component: api
  ports:
  - port: 80
    targetPort: 8080
---
## Deployment of the Pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 3
  selector:
    matchLabels:
      component: api
  template:
    metadata:
      labels: 
        component: api
    spec:
      containers:
        - name: api
          image: kvital/simplechat-api
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"